/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as PostsCreateRouteImport } from './routes/posts/create'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountHomeRouteImport } from './routes/account/home'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsCreateRoute = PostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHomeRoute = AccountHomeRouteImport.update({
  id: '/account/home',
  path: '/account/home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/home': typeof AccountHomeRoute
  '/account/register': typeof AccountRegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/account': typeof AccountIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/home': typeof AccountHomeRoute
  '/account/register': typeof AccountRegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/account': typeof AccountIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/home': typeof AccountHomeRoute
  '/account/register': typeof AccountRegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/account/': typeof AccountIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/home'
    | '/account/register'
    | '/posts/create'
    | '/account'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/home'
    | '/account/register'
    | '/posts/create'
    | '/account'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/account/home'
    | '/account/register'
    | '/posts/create'
    | '/account/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountHomeRoute: typeof AccountHomeRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  PostsCreateRoute: typeof PostsCreateRoute
  AccountIndexRoute: typeof AccountIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/create': {
      id: '/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof PostsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/home': {
      id: '/account/home'
      path: '/account/home'
      fullPath: '/account/home'
      preLoaderRoute: typeof AccountHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountHomeRoute: AccountHomeRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  PostsCreateRoute: PostsCreateRoute,
  AccountIndexRoute: AccountIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
